DROP INDEX IF EXISTS users_email_idx;

DROP TABLE IF EXISTS user_app_profiles CASCADE;
DROP TABLE IF EXISTS user_profiles CASCADE;

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS apps CASCADE;

DROP TYPE IF EXISTS TOKEN_TYPE;
DROP TYPE IF EXISTS AUTH_METHOD;
DROP TYPE IF EXISTS APP_ROLE;
